id: P31843E90
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN9314
  title: རྒྱལ་སྲས་ཀྱི་སྤྱོད་ལ་འཇུག་པའི་ཆོས་སྐོར།
  volumes:
    e99cea7e2bd841119eeb5e2332fc5786:
      image_group_id: I3CN9316
      title: ''
      base_file: v001.txt
  author: ''
